# Generated by Django 4.2.5 on 2024-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='flesh',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='legs',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='whole_chickens',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='wings',
        ),
        migrations.AddField(
            model_name='inventory',
            name='chickens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
